name: Deploy
on:
  repository_dispatch:
    types: [deploy]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: actions/ansible-cli-action@latest
        with:
          command: "make deploy"
