name: Deploy
on:
  repository_dispatch:
    types: [deploy]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: main.yml
          directory: ./
          vault_password: ${{secrets.ANSIBLE_VAULT}}
          options: |
            --inventory host.ini
            --verbose
            --extra-vars "ENV=dev VERSION=1"
            --tags "deploy"
