name: Deploy
on:
  repository_dispatch:
    types: [deploy]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
      - uses: saubermacherag/ansible-playbook-docker-action@v1.4
        with:
          playbookName: 'main.yml'
          inventoryFile: 'host.ini'
          verbosity: "vv"
